go snapshotter: generate smaller diffs
By using another library that provides contextual diffing, we get line
numbers of where our diffs are and smaller diffs for significant
snapshot differences.

```
--- FAIL: TestSnapshotter (0.00s)
	snapshotter_test.go:17: snapshot second differs:
		--- expected
		+++ received
		@@ -1,2 +1,2 @@
		-[2,
		- {Foo: "Bar"}]
		+[5,
		+ {Foo: "Foo"}]
	snapshotter_test.go:17: If this is intentional, you can run `go test . -rewriteSnapshots` to generate new snapshots.
FAIL
exit status 1
FAIL	github.com/samsarahq/go/snapshotter	0.007s
```

instead of this:

```
--- FAIL: TestSnapshotter (0.00s)
	snapshotter_test.go:17: snapshot second differs:
		 [
		- 2,
		+ 5,
		  {
		-  Foo: "Bar",
		+  Foo: "Foo",
		  },
		 ]
	snapshotter_test.go:17: If this is intentional, you can run `go test . -rewriteSnapshots` to generate new snapshots.
FAIL
exit status 1
FAIL	github.com/samsarahq/go/snapshotter	0.007s
```